FROM quay.io/quarkus/quarkus-distroless-image:2.0

COPY --chown=nonroot target/*-runner /work/application

EXPOSE 8080 8443
USER nonroot
ENTRYPOINT ["/work/application", "-Dquarkus.http.host=0.0.0.0"]
