quarkus.lambda.handler=rest-handler
quarkus.http.port=8080

express-compute.clusters-table=${ECP_CLUSTERS_TABLE:express-compute-clusters}
express-compute.associations-table=${ECP_ASSOCIATIONS_TABLE:express-compute-associations}

mp.jwt.verify.audiences=pods.eks.amazonaws.com
aws.sts.session-duration=PT1H

quarkus.log.level=INFO
quarkus.log.category."ai.codriverlabs".level=DEBUG
