---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: eks-dx-auth-proxy-selfsigned
  namespace: kube-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eks-dx-auth-proxy-ca
  namespace: kube-system
spec:
  isCA: true
  commonName: eks-dx-auth-proxy-ca
  secretName: eks-dx-auth-proxy-ca
  issuerRef:
    name: eks-dx-auth-proxy-selfsigned
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: eks-dx-auth-proxy-ca
  namespace: kube-system
spec:
  ca:
    secretName: eks-dx-auth-proxy-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eks-dx-auth-proxy-cert
  namespace: kube-system
spec:
  secretName: eks-dx-auth-proxy-tls
  duration: 8760h   # 1 year
  renewBefore: 720h # 30 days
  issuerRef:
    name: eks-dx-auth-proxy-ca
    kind: Issuer
  dnsNames:
  - eks-dx-auth-proxy.kube-system.svc
  - eks-dx-auth-proxy.kube-system.svc.cluster.local
