FROM registry.access.redhat.com/ubi8/openjdk-21:1.20

ENV LANGUAGE='en_US:en'

# Copy the native executable
COPY --chown=185 target/*-runner /work/application

EXPOSE 8080
USER 185
ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]
