quarkus.lambda.handler=rest-handler
quarkus.http.port=8080

eks-dx.clusters-table=${EKS_DX_CLUSTERS_TABLE:eks-dx-clusters}
eks-dx.associations-table=${EKS_DX_ASSOCIATIONS_TABLE:eks-dx-associations}

mp.jwt.verify.audiences=pods.eks.amazonaws.com
aws.sts.session-duration=PT1H

quarkus.snapstart.enable=true
quarkus.log.level=INFO
quarkus.log.category."ai.codriverlabs".level=DEBUG
